name: Integration Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs: {}

jobs:
  gradle-wrapper-validation:

    name: "Validate Gradle Wrapper"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: gradle/wrapper-validation-action@v1

  build:

    name: "Build and test project"
    runs-on: ${{ matrix.platform }}
    needs: gradle-wrapper-validation

    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]

    steps:
    # Setup environment
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    # Setup caches
    - name: Cache for Gradle
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: "gradle-\
          ${{runner.os}}-\
          ${{hashFiles('gradle/wrapper/gradle-wrapper.properties')}}-\
          ${{hashFiles('gradle.lockfile')}}"
    # Build
    - name: Build with Gradle
      run: ./gradlew projectReport build
    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/libs/
    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: build-reports
        path: build/reports/
