name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: The target branch for the created pull request
        required: false
        default: ${{ github.ref }}

jobs:
  build:

    name: "Build and test project"
    runs-on: ubuntu-latest

    steps:
    # Setup environment
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Prepare local actions
      uses: JojOatXGME/prepare-local-actions@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    # Setup caches
    - name: Cache for Gradle
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: "gradle-\
          ${{ runner.os }}-\
          ${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-\
          ${{ hashFiles('gradle.lockfile') }}"
    # todo ...
    # todo Update README.md
    # todo Check I'm on the right branch (prevent release creation from other branches)
    # Build
    - name: Build with Gradle
      run: ./gradlew projectReport buildRelease
    - name: Upload build reports
      if: steps.gradle-build.outcome == 'success' || steps.gradle-build.outcome == 'failure'
      uses: actions/upload-artifact@v2
      with:
        name: build-reports
        path: build/reports/
        if-no-files-found: ignore
    # Create pull request
    - name: Create pull request
      uses: ./.github/actions/create-pull-request-for-release
      with:
        name: Release ${{ version }}
        label: release
        target_branch: ${{ github.event.inputs.target_branch }}
        exclude: |
          ./.github
          ./.gradle
        var_version: ${{ version }}
